### ISSUE TITLE
Bot creates new labels

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs-github-bot/github-bot#50]
I am not sure, but I think the bot just created a new label `platform_tools` at submission of my PR, which probably is unintentional.

**Comment by phillipj** [comment]
Thanks for reporting 👍

Refs https://github.com/nodejs/node/pull/7440

**Comment by phillipj** [comment]
It's because it matches everything in `deps/` as its own label. Since you've commited a bunch of files in the `deps/platform_tools` directory, the PR automatically gets labeled with `platform_tools`.

If the proposal gets merged, and the label is not correct, we'll fix it. In the meantime you could just remove the label, as the bot wont re-add it again.

**Comment by eljefedelrodeodeljefe** [comment]
Alright. Thanks for the info. There likely won't be many `deps` PRs
